//! Call/session data types shared by telephony modules.

use crate::{Error, Result};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::{Arc, RwLock};

/// Stable call identifier assigned by the telephony transport.
pub type CallId = String;

/// Stable call-leg identifier for one participant/media direction.
pub type CallLegId = String;

/// Direction of the call from the gateway's perspective.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CallDirection {
    /// Remote peer called into the gateway.
    Inbound,
    /// Gateway dialed a remote peer.
    Outbound,
    /// Session is a SIPREC mirrored recording.
    SiprecMirror,
}

/// Participant role attached to per-frame metadata.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ParticipantRole {
    /// End user/caller.
    User,
    /// Client/agent side of a call.
    Client,
    /// Bot media generated by the pipeline.
    Bot,
    /// Unknown or unclassified participant.
    Unknown,
}

/// High-level call session lifecycle.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CallSessionState {
    /// SIP dialog or outbound dial is being negotiated.
    Negotiating,
    /// Media is active and associated with a pipeline session.
    Active,
    /// Teardown has started but cleanup is not complete.
    Terminating,
    /// Session completed normally.
    Terminated,
    /// Session failed.
    Failed,
}

/// Metadata describing one active or recently terminated call session.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CallSession {
    /// Transport call identifier.
    pub call_id: CallId,
    /// SIP Call-ID or upstream correlation ID.
    pub external_call_id: Option<String>,
    /// Call direction.
    pub direction: CallDirection,
    /// Current lifecycle state.
    pub state: CallSessionState,
    /// Known call legs.
    pub legs: Vec<CallLegId>,
}

impl CallSession {
    /// Create a new call session in negotiation state.
    pub fn new(call_id: CallId, direction: CallDirection) -> Self {
        Self {
            call_id,
            external_call_id: None,
            direction,
            state: CallSessionState::Negotiating,
            legs: Vec::new(),
        }
    }

    /// Transition the session state.
    pub fn transition_to(&mut self, next: CallSessionState) -> Result<()> {
        if !is_valid_transition(self.state, next) {
            return Err(Error::Session(format!(
                "invalid call session transition from {:?} to {:?}",
                self.state, next
            )));
        }

        self.state = next;
        Ok(())
    }
}

/// In-memory call session registry.
#[derive(Debug, Clone, Default)]
pub struct CallSessionRegistry {
    sessions: Arc<RwLock<HashMap<CallId, CallSession>>>,
}

impl CallSessionRegistry {
    /// Insert a new session.
    pub fn insert(&self, session: CallSession) -> Result<()> {
        let mut sessions = self
            .sessions
            .write()
            .map_err(|_| Error::Session("call session registry lock poisoned".to_string()))?;

        if sessions.contains_key(&session.call_id) {
            return Err(Error::Session(format!(
                "call session already exists: {}",
                session.call_id
            )));
        }

        sessions.insert(session.call_id.clone(), session);
        Ok(())
    }

    /// Fetch a session snapshot.
    pub fn get(&self, call_id: &str) -> Result<Option<CallSession>> {
        let sessions = self
            .sessions
            .read()
            .map_err(|_| Error::Session("call session registry lock poisoned".to_string()))?;
        Ok(sessions.get(call_id).cloned())
    }

    /// Transition an existing session.
    pub fn transition(&self, call_id: &str, next: CallSessionState) -> Result<()> {
        let mut sessions = self
            .sessions
            .write()
            .map_err(|_| Error::Session("call session registry lock poisoned".to_string()))?;
        let session = sessions
            .get_mut(call_id)
            .ok_or_else(|| Error::Session(format!("unknown call session: {call_id}")))?;
        session.transition_to(next)
    }

    /// Number of tracked sessions.
    pub fn len(&self) -> Result<usize> {
        let sessions = self
            .sessions
            .read()
            .map_err(|_| Error::Session("call session registry lock poisoned".to_string()))?;
        Ok(sessions.len())
    }

    /// Return all tracked call IDs.
    pub fn call_ids(&self) -> Result<Vec<CallId>> {
        let sessions = self
            .sessions
            .read()
            .map_err(|_| Error::Session("call session registry lock poisoned".to_string()))?;
        Ok(sessions.keys().cloned().collect())
    }

    /// True if no sessions are tracked.
    pub fn is_empty(&self) -> Result<bool> {
        Ok(self.len()? == 0)
    }
}

impl ParticipantRole {
    /// Canonical participant role string used by RemoteMedia frame metadata.
    pub fn as_participant_role(self) -> &'static str {
        match self {
            // Telephony's historical `User` leg maps to the pipeline owner /
            // local user role in the transport-neutral vocabulary.
            ParticipantRole::User => remotemedia_core::transport::data::participant::role::USER,
            ParticipantRole::Client => remotemedia_core::transport::data::participant::role::CLIENT,
            // Bot is not a reserved participant role; `copilot` is the closest
            // shared role for assistant-generated media.
            ParticipantRole::Bot => remotemedia_core::transport::data::participant::role::COPILOT,
            ParticipantRole::Unknown => "unknown",
        }
    }
}

fn is_valid_transition(current: CallSessionState, next: CallSessionState) -> bool {
    use CallSessionState::*;
    matches!(
        (current, next),
        (Negotiating, Active)
            | (Negotiating, Terminating)
            | (Negotiating, Failed)
            | (Active, Terminating)
            | (Active, Failed)
            | (Terminating, Terminated)
            | (Terminating, Failed)
            | (Failed, Terminated)
    ) || current == next
}

/// Metadata keys used on `TransportData` frames emitted by this transport.
pub mod metadata_keys {
    /// Transport call identifier.
    pub const CALL_ID: &str = "telephony.call_id";
    /// Call leg identifier.
    pub const LEG_ID: &str = "telephony.leg_id";
    /// Participant role.
    pub const PARTICIPANT_ROLE: &str = "telephony.participant_role";
    /// RTP timestamp associated with the source packet/frame.
    pub const RTP_TIMESTAMP: &str = "telephony.rtp_timestamp";
    /// RTP sequence number associated with the source packet/frame.
    pub const RTP_SEQUENCE: &str = "telephony.rtp_sequence";
    /// Negotiated codec.
    pub const CODEC: &str = "telephony.codec";
    /// Audio sample rate in Hz.
    pub const SAMPLE_RATE_HZ: &str = "telephony.sample_rate_hz";
}

/// Apply standard telephony metadata to a `TransportData` value.
pub fn apply_frame_metadata(
    mut data: remotemedia_core::transport::TransportData,
    call_id: &str,
    leg_id: &str,
    role: ParticipantRole,
    codec: &str,
    sample_rate_hz: u32,
    rtp_timestamp: Option<u32>,
    rtp_sequence: Option<u16>,
) -> remotemedia_core::transport::TransportData {
    use remotemedia_core::transport::data::participant;

    data.metadata
        .insert(metadata_keys::CALL_ID.to_string(), call_id.to_string());
    data.metadata
        .insert(metadata_keys::LEG_ID.to_string(), leg_id.to_string());
    data.metadata.insert(
        metadata_keys::PARTICIPANT_ROLE.to_string(),
        format!("{role:?}").to_lowercase(),
    );
    data.metadata
        .insert(participant::ID.to_string(), leg_id.to_string());
    data.metadata.insert(
        participant::ROLE.to_string(),
        role.as_participant_role().to_string(),
    );
    data.metadata
        .insert(participant::TRACK_ID.to_string(), leg_id.to_string());
    data.metadata.insert(
        participant::MODALITY.to_string(),
        participant::modality::AUDIO.to_string(),
    );
    data.metadata
        .insert(metadata_keys::CODEC.to_string(), codec.to_string());
    data.metadata.insert(
        metadata_keys::SAMPLE_RATE_HZ.to_string(),
        sample_rate_hz.to_string(),
    );
    if let Some(ts) = rtp_timestamp {
        data.metadata
            .insert(metadata_keys::RTP_TIMESTAMP.to_string(), ts.to_string());
    }
    if let Some(seq) = rtp_sequence {
        data.metadata
            .insert(metadata_keys::RTP_SEQUENCE.to_string(), seq.to_string());
    }
    data
}

#[cfg(test)]
mod tests {
    use super::*;
    use remotemedia_core::data::RuntimeData;
    use remotemedia_core::transport::TransportData;

    #[test]
    fn enforces_lifecycle_transitions() {
        let mut session = CallSession::new("call-1".into(), CallDirection::Inbound);
        session.transition_to(CallSessionState::Active).unwrap();
        session
            .transition_to(CallSessionState::Terminating)
            .unwrap();
        session.transition_to(CallSessionState::Terminated).unwrap();
        assert!(session.transition_to(CallSessionState::Active).is_err());
    }

    #[test]
    fn registry_tracks_sessions() {
        let registry = CallSessionRegistry::default();
        registry
            .insert(CallSession::new("call-1".into(), CallDirection::Inbound))
            .unwrap();
        assert_eq!(registry.len().unwrap(), 1);
        registry
            .transition("call-1", CallSessionState::Active)
            .unwrap();
        assert_eq!(
            registry.get("call-1").unwrap().unwrap().state,
            CallSessionState::Active
        );
    }

    #[test]
    fn applies_frame_metadata() {
        let data = apply_frame_metadata(
            TransportData::new(RuntimeData::Text("x".into())),
            "call",
            "leg",
            ParticipantRole::User,
            "opus",
            48_000,
            Some(10),
            Some(20),
        );

        assert_eq!(data.get_metadata(metadata_keys::CALL_ID).unwrap(), "call");
        assert_eq!(data.participant_id().unwrap(), "leg");
        assert_eq!(data.participant_role().unwrap(), "user");
        assert_eq!(
            data.get_metadata(remotemedia_core::transport::data::participant::TRACK_ID)
                .unwrap(),
            "leg"
        );
        assert_eq!(
            data.get_metadata(remotemedia_core::transport::data::participant::MODALITY)
                .unwrap(),
            "audio"
        );
        assert_eq!(
            data.get_metadata(metadata_keys::RTP_SEQUENCE).unwrap(),
            "20"
        );
    }
}
