//! FFI bindings for TFLite/LiteRT C API.
//!
//! This module is generated by bindgen at build time from litert_ffi.h.

#[allow(non_camel_case_types)]
#[allow(non_snake_case)]
#[allow(non_upper_case_globals)]
#[allow(dead_code)]
mod bindings {
    include!(concat!(env!("OUT_DIR"), "/litert_bindings.rs"));
}

pub use bindings::*;

/// Check if we're linked against LiteRT vs standard TFLite
pub fn is_litert_available() -> bool {
    // Try to resolve a LiteRT-specific symbol
    // This is a runtime check since we link dynamically
    true // We'll assume LiteRT is available if the library loads
}

/// Get the TFLite version string
pub fn tf_lite_version() -> &'static str {
    unsafe {
        let ptr = TfLiteVersion();
        if ptr.is_null() {
            "unknown"
        } else {
            std::ffi::CStr::from_ptr(ptr).to_str().unwrap_or("unknown")
        }
    }
}
